### ISSUE TITLE
3dsx build doesn't boot- hangs on red screen.

### ISSUE THREAD

**Issue by Rust-and-Sunset** [llakssz/CIAngel#132]
^ Title, really. Not much else to it.

11.3 (EUR) N3DSXL, booting from GridLauncher. Replaced the previous release's .3dsx with the new version.

**Comment by noirscape** [comment]
Do you have arm9loaderhax (I assume so since this is a tool that only
really works if you have CFW)? If so, use the CIA build. If you don't,
install arm9loaderhax through the Guide (https://3ds.guide).

If I recall correctly, 3dsx homebrew doesn't always work properly starting
from 11.3 for some reason.

**Comment by DrakiaXYZ** [comment]
I honestly can't be bothered fixing the .3dsx version, it's a crippled implementation with only the ability to create .cia files, and no installation capabilities.

So unless someone else fixes it, and makes a PR, this is unlikely to get resolved, and I'll be pulling the 3dsx release next time we make an update.

**Comment by Rust-and-Sunset** [comment]
In that case, I might as well just switch to FreeShop- the 3dsx build was the only significant advantage CIAngel had.

Cheers for the response, anyway.

**Comment by DrakiaXYZ** [comment]
Besides not requiring a cache, the ability to create CIAs, and less crashing, sure, no advantages here.
