### ISSUE TITLE
Add a queue

### ISSUE THREAD

**Issue by llakssz** [llakssz/CIAngel#39]
Upon selecting a title to download/install, able to press A to initiate immediately, or able to press X (for example), to add to the queue.
'Process Queue - N items ' will be a new main menu item, where the queue will be started.
All items in the queue will use the current install method (cia/install/ticket).
Queued items can simply be a struct on a vector, containing all the necessary information needed for all install methods, for example titleid, key, full output path, data in struct is used as necessary for the current install method.

**Comment by ghost** [comment]
Or maybe instead of a whole new menu, if you had search results:
1. Animal Crossing USA
2. Cave Story USA

You could type 2 and just press X to add to Queue or press A to initiate. This could work for all the download/install options too! You could press X on the input.txt option or X on the TitleID/Key option.
This way would be much faster and would reduce unnecessary code

**Comment by llakssz** [comment]
No typing numbers anymore, the game is selected via UP and DOWN

**Comment by ghost** [comment]
Oh ok, then when you have the selection over a game, just press X or A?

**Comment by ghost** [comment]
Could you press B to cancel downloading/installing a CIA too? This could probably be last on your list

**Comment by DrakiaXYZ** [comment]
I'll be taking over this one and working on implementing a download queue

**Comment by DrakiaXYZ** [comment]
Making progress on this, had to change how menus are handled which made them quite a bit more complicated (Since we have to be able to handle non-A keypresses for this, it has to use a callback and be able to pass data on to that callback. Fun times, hopefully it's not too complicated).

Should be able to finish this up tomorrow or the day after :)

**Comment by llakssz** [comment]
I'm interested to see it! Sounds good, good luck

**Comment by DrakiaXYZ** [comment]
https://github.com/llakssz/CIAngel/pull/43
